// <auto-generated />
using System;
using LockedIn.DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LockedIn.DataAccess.Migrations
{
    [DbContext(typeof(LockedInDbContext))]
    [Migration("20260702182100_AddWorkspaceSessions")]
    partial class AddWorkspaceSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LockedIn.DataAccess.Models.AiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("feature");

                    b.Property<Guid>("PtProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pt_profile_id");

                    b.Property<int>("TokenUsed")
                        .HasColumnType("int")
                        .HasColumnName("token_used");

                    b.HasKey("Id")
                        .HasName("PK__ai_usage__3213E83F94E74880");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_ai_usage_logs_created_at");

                    b.HasIndex(new[] { "PtProfileId" }, "ix_ai_usage_logs_pt_profile_id");

                    b.ToTable("ai_usage_logs", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("entity_name");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("metadata_json");

                    b.HasKey("Id")
                        .HasName("PK__audit_lo__3213E83F4EF56003");

                    b.HasIndex(new[] { "ActorUserId" }, "ix_audit_logs_actor_user_id");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_audit_logs_created_at");

                    b.HasIndex(new[] { "EntityName", "EntityId" }, "ix_audit_logs_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("package_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("PtProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pt_profile_id");

                    b.Property<int>("SessionCount")
                        .HasColumnType("int")
                        .HasColumnName("session_count");

                    b.Property<DateTime?>("SettlementDueAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("settlement_due_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__bookings__3213E83FD21291C7");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_bookings_created_at");

                    b.HasIndex(new[] { "CustomerId" }, "ix_bookings_customer_id");

                    b.HasIndex(new[] { "PackageId" }, "ix_bookings_package_id");

                    b.HasIndex(new[] { "PtProfileId" }, "ix_bookings_pt_profile_id");

                    b.HasIndex(new[] { "Status" }, "ix_bookings_status");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("FirebaseConversationId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("firebase_conversation_id");

                    b.Property<Guid>("PtProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pt_profile_id");

                    b.HasKey("Id")
                        .HasName("PK__conversa__3213E83F4A447B13");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PtProfileId");

                    b.HasIndex(new[] { "BookingId" }, "UQ__conversa__5DE3A5B065808E54")
                        .IsUnique();

                    b.HasIndex(new[] { "FirebaseConversationId" }, "UQ__conversa__C704B367F57EC45D")
                        .IsUnique();

                    b.HasIndex(new[] { "BookingId" }, "ux_conversations_booking_id")
                        .IsUnique();

                    b.HasIndex(new[] { "FirebaseConversationId" }, "ux_conversations_firebase_id")
                        .IsUnique();

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("FitnessGoal")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fitness_goal");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gender");

                    b.Property<string>("HealthNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("health_note");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("height_cm");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("PK__customer__3213E83F7EEE07E2");

                    b.HasIndex("DeletedBy");

                    b.HasIndex(new[] { "UserId" }, "UQ__customer__B9BE370E5DAC7E13")
                        .IsUnique();

                    b.HasIndex(new[] { "IsDeleted" }, "ix_customer_profiles_is_deleted");

                    b.HasIndex(new[] { "UserId" }, "ux_customer_profiles_user_id")
                        .IsUnique();

                    b.ToTable("customer_profiles", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("PtProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pt_profile_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reason");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByAdminId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("resolved_by_admin_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__disputes__3213E83F9BA14776");

                    b.HasIndex("ResolvedByAdminId");

                    b.HasIndex(new[] { "BookingId" }, "ix_disputes_booking_id");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_disputes_created_at");

                    b.HasIndex(new[] { "CustomerId" }, "ix_disputes_customer_id");

                    b.HasIndex(new[] { "PtProfileId" }, "ix_disputes_pt_profile_id");

                    b.HasIndex(new[] { "Status" }, "ix_disputes_status");

                    b.HasIndex(new[] { "BookingId" }, "ux_disputes_one_open_per_booking")
                        .IsUnique()
                        .HasFilter("([status] IN ((1), (2), (3)))");

                    b.ToTable("disputes", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.DisputeEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("dispute_id");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_url");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__dispute___3213E83F1F7FC76C");

                    b.HasIndex(new[] { "DisputeId" }, "ix_dispute_evidences_dispute_id");

                    b.ToTable("dispute_evidences", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CreatedByPtId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_pt_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("PK__meal_pla__3213E83FE8434E9A");

                    b.HasIndex("DeletedBy");

                    b.HasIndex(new[] { "CreatedByPtId" }, "ix_meal_plans_created_by_pt_id");

                    b.HasIndex(new[] { "IsActive" }, "ix_meal_plans_is_active");

                    b.HasIndex(new[] { "IsDeleted" }, "ix_meal_plans_is_deleted");

                    b.HasIndex(new[] { "WorkspaceId" }, "ix_meal_plans_workspace_id");

                    b.ToTable("meal_plans", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__notifica__3213E83FD17F67A2");

                    b.HasIndex("DeletedBy");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_notifications_created_at");

                    b.HasIndex(new[] { "IsDeleted" }, "ix_notifications_is_deleted");

                    b.HasIndex(new[] { "IsRead" }, "ix_notifications_is_read");

                    b.HasIndex(new[] { "UserId" }, "ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("price");

                    b.Property<Guid>("PtProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pt_profile_id");

                    b.Property<int>("SessionCount")
                        .HasColumnType("int")
                        .HasColumnName("session_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__packages__3213E83F330FC9D4");

                    b.HasIndex("DeletedBy");

                    b.HasIndex(new[] { "IsActive" }, "ix_packages_is_active");

                    b.HasIndex(new[] { "IsDeleted" }, "ix_packages_is_deleted");

                    b.HasIndex(new[] { "Price" }, "ix_packages_price");

                    b.HasIndex(new[] { "PtProfileId" }, "ix_packages_pt_profile_id");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("checkout_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired_at");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("order_code");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PayOS")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__payments__3213E83FEDB87C2A");

                    b.HasIndex(new[] { "OrderCode" }, "UQ__payments__99D12D3FD8197709")
                        .IsUnique();

                    b.HasIndex(new[] { "BookingId" }, "ix_payments_booking_id");

                    b.HasIndex(new[] { "Status" }, "ix_payments_status");

                    b.HasIndex(new[] { "BookingId" }, "ux_payments_one_success_per_booking")
                        .IsUnique()
                        .HasFilter("([status]=(2))");

                    b.HasIndex(new[] { "OrderCode" }, "ux_payments_order_code")
                        .IsUnique();

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.PaymentWebhookLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsValidSignature")
                        .HasColumnType("bit")
                        .HasColumnName("is_valid_signature");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PayOS")
                        .HasColumnName("provider");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_payload");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__payment___3213E83F77B7BFB3");

                    b.HasIndex(new[] { "EventId" }, "ix_payment_webhook_logs_event_id");

                    b.HasIndex(new[] { "PaymentId" }, "ix_payment_webhook_logs_payment_id");

                    b.HasIndex(new[] { "ReceivedAt" }, "ix_payment_webhook_logs_received_at");

                    b.ToTable("payment_webhook_logs", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.PtDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("document_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_url");

                    b.Property<Guid>("PtProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pt_profile_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Id")
                        .HasName("PK__pt_docum__3213E83F008BB1B4");

                    b.HasIndex(new[] { "DocumentType" }, "ix_pt_documents_document_type");

                    b.HasIndex(new[] { "PtProfileId" }, "ix_pt_documents_pt_profile_id");

                    b.HasIndex(new[] { "Status" }, "ix_pt_documents_status");

                    b.ToTable("pt_documents", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.PtProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("average_rating");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("specialization");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("total_reviews");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("VerificationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("PK__pt_profi__3213E83F912EDD79");

                    b.HasIndex("DeletedBy");

                    b.HasIndex(new[] { "UserId" }, "UQ__pt_profi__B9BE370E276F861C")
                        .IsUnique();

                    b.HasIndex(new[] { "AverageRating" }, "ix_pt_profiles_average_rating");

                    b.HasIndex(new[] { "IsDeleted" }, "ix_pt_profiles_is_deleted");

                    b.HasIndex(new[] { "VerificationStatus" }, "ix_pt_profiles_verification_status");

                    b.HasIndex(new[] { "UserId" }, "ux_pt_profiles_user_id")
                        .IsUnique();

                    b.ToTable("pt_profiles", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__refresh___3213E83FB90CC2E0");

                    b.HasIndex(new[] { "ExpiresAt" }, "ix_refresh_tokens_expires_at");

                    b.HasIndex(new[] { "UserId" }, "ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("is_hidden");

                    b.Property<Guid>("PtProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pt_profile_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__reviews__3213E83FC246B2B0");

                    b.HasIndex(new[] { "BookingId" }, "UQ__reviews__5DE3A5B06B553922")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomerId" }, "ix_reviews_customer_id");

                    b.HasIndex(new[] { "IsHidden" }, "ix_reviews_is_hidden");

                    b.HasIndex(new[] { "PtProfileId" }, "ix_reviews_pt_profile_id");

                    b.HasIndex(new[] { "BookingId" }, "ux_reviews_booking_id")
                        .IsUnique();

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("net_amount");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("platform_fee");

                    b.Property<Guid>("PtProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pt_profile_id");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("settled_at");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__settleme__3213E83FC82FEC5F");

                    b.HasIndex(new[] { "BookingId" }, "UQ__settleme__5DE3A5B0FE34E5F5")
                        .IsUnique();

                    b.HasIndex(new[] { "PtProfileId" }, "ix_settlements_pt_profile_id");

                    b.HasIndex(new[] { "Status" }, "ix_settlements_status");

                    b.HasIndex(new[] { "BookingId" }, "ux_settlements_booking_id")
                        .IsUnique();

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("email_verified");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83FD1C72651");

                    b.HasIndex("DeletedBy");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164EEF4CB86")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "ix_users_email");

                    b.HasIndex(new[] { "IsDeleted" }, "ix_users_is_deleted");

                    b.HasIndex(new[] { "Role" }, "ix_users_role");

                    b.HasIndex(new[] { "Status" }, "ix_users_status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("booking_id");

                    b.Property<string>("CourseNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("course_note");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("PtProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pt_profile_id");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__workspac__3213E83FDD6DCD60");

                    b.HasIndex(new[] { "BookingId" }, "UQ__workspac__5DE3A5B0181B9644")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomerId" }, "ix_workspaces_customer_id");

                    b.HasIndex(new[] { "PtProfileId" }, "ix_workspaces_pt_profile_id");

                    b.HasIndex(new[] { "Status" }, "ix_workspaces_status");

                    b.HasIndex(new[] { "BookingId" }, "ux_workspaces_booking_id")
                        .IsUnique();

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.WorkspaceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int")
                        .HasColumnName("session_number");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("PK__workspace_sessions__3213E83FD1C72652");

                    b.HasIndex(new[] { "WorkspaceId", "SessionNumber" }, "uq_workspace_sessions_workspace_id_session_number")
                        .IsUnique();

                    b.ToTable("workspace_sessions", (string)null);
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.AiUsageLog", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "PtProfile")
                        .WithMany("AiUsageLogs")
                        .HasForeignKey("PtProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_ai_usage_logs_pt_profile_id");

                    b.Navigation("PtProfile");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.AuditLog", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .HasConstraintName("fk_audit_logs_actor_user_id");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Booking", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.CustomerProfile", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_bookings_customer_id");

                    b.HasOne("LockedIn.DataAccess.Models.Package", "Package")
                        .WithMany("Bookings")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("fk_bookings_package_id");

                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "PtProfile")
                        .WithMany("Bookings")
                        .HasForeignKey("PtProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_bookings_pt_profile_id");

                    b.Navigation("Customer");

                    b.Navigation("Package");

                    b.Navigation("PtProfile");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Conversation", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.Booking", "Booking")
                        .WithOne("Conversation")
                        .HasForeignKey("LockedIn.DataAccess.Models.Conversation", "BookingId")
                        .IsRequired()
                        .HasConstraintName("fk_conversations_booking_id");

                    b.HasOne("LockedIn.DataAccess.Models.CustomerProfile", "Customer")
                        .WithMany("Conversations")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_conversations_customer_id");

                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "PtProfile")
                        .WithMany("Conversations")
                        .HasForeignKey("PtProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_conversations_pt_profile_id");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("PtProfile");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.CustomerProfile", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.User", "DeletedByNavigation")
                        .WithMany("CustomerProfileDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("fk_customer_profiles_deleted_by");

                    b.HasOne("LockedIn.DataAccess.Models.User", "User")
                        .WithOne("CustomerProfileUser")
                        .HasForeignKey("LockedIn.DataAccess.Models.CustomerProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("fk_customer_profiles_user_id");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Dispute", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.Booking", "Booking")
                        .WithOne("Dispute")
                        .HasForeignKey("LockedIn.DataAccess.Models.Dispute", "BookingId")
                        .IsRequired()
                        .HasConstraintName("fk_disputes_booking_id");

                    b.HasOne("LockedIn.DataAccess.Models.CustomerProfile", "Customer")
                        .WithMany("Disputes")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_disputes_customer_id");

                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "PtProfile")
                        .WithMany("Disputes")
                        .HasForeignKey("PtProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_disputes_pt_profile_id");

                    b.HasOne("LockedIn.DataAccess.Models.User", "ResolvedByAdmin")
                        .WithMany("Disputes")
                        .HasForeignKey("ResolvedByAdminId")
                        .HasConstraintName("fk_disputes_resolved_by_admin_id");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("PtProfile");

                    b.Navigation("ResolvedByAdmin");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.DisputeEvidence", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.Dispute", "Dispute")
                        .WithMany("DisputeEvidences")
                        .HasForeignKey("DisputeId")
                        .IsRequired()
                        .HasConstraintName("fk_dispute_evidences_dispute_id");

                    b.Navigation("Dispute");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.MealPlan", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "CreatedByPt")
                        .WithMany("MealPlans")
                        .HasForeignKey("CreatedByPtId")
                        .IsRequired()
                        .HasConstraintName("fk_meal_plans_created_by_pt_id");

                    b.HasOne("LockedIn.DataAccess.Models.User", "DeletedByNavigation")
                        .WithMany("MealPlans")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("fk_meal_plans_deleted_by");

                    b.HasOne("LockedIn.DataAccess.Models.Workspace", "Workspace")
                        .WithMany("MealPlans")
                        .HasForeignKey("WorkspaceId")
                        .IsRequired()
                        .HasConstraintName("fk_meal_plans_workspace_id");

                    b.Navigation("CreatedByPt");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Notification", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.User", "DeletedByNavigation")
                        .WithMany("NotificationDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("fk_notifications_deleted_by");

                    b.HasOne("LockedIn.DataAccess.Models.User", "User")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_notifications_user_id");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Package", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.User", "DeletedByNavigation")
                        .WithMany("Packages")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("fk_packages_deleted_by");

                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "PtProfile")
                        .WithMany("Packages")
                        .HasForeignKey("PtProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_packages_pt_profile_id");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("PtProfile");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Payment", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("LockedIn.DataAccess.Models.Payment", "BookingId")
                        .IsRequired()
                        .HasConstraintName("fk_payments_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.PaymentWebhookLog", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.Payment", "Payment")
                        .WithMany("PaymentWebhookLogs")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("fk_payment_webhook_logs_payment_id");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.PtDocument", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "PtProfile")
                        .WithMany("PtDocuments")
                        .HasForeignKey("PtProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_pt_documents_pt_profile_id");

                    b.Navigation("PtProfile");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.PtProfile", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.User", "DeletedByNavigation")
                        .WithMany("PtProfileDeletedByNavigations")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("fk_pt_profiles_deleted_by");

                    b.HasOne("LockedIn.DataAccess.Models.User", "User")
                        .WithOne("PtProfileUser")
                        .HasForeignKey("LockedIn.DataAccess.Models.PtProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("fk_pt_profiles_user_id");

                    b.Navigation("DeletedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.RefreshToken", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Review", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("LockedIn.DataAccess.Models.Review", "BookingId")
                        .IsRequired()
                        .HasConstraintName("fk_reviews_booking_id");

                    b.HasOne("LockedIn.DataAccess.Models.CustomerProfile", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_reviews_customer_id");

                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "PtProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("PtProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_reviews_pt_profile_id");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("PtProfile");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Settlement", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.Booking", "Booking")
                        .WithOne("Settlement")
                        .HasForeignKey("LockedIn.DataAccess.Models.Settlement", "BookingId")
                        .IsRequired()
                        .HasConstraintName("fk_settlements_booking_id");

                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "PtProfile")
                        .WithMany("Settlements")
                        .HasForeignKey("PtProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_settlements_pt_profile_id");

                    b.Navigation("Booking");

                    b.Navigation("PtProfile");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.User", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.User", "DeletedByNavigation")
                        .WithMany("InverseDeletedByNavigation")
                        .HasForeignKey("DeletedBy")
                        .HasConstraintName("fk_users_deleted_by");

                    b.Navigation("DeletedByNavigation");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Workspace", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.Booking", "Booking")
                        .WithOne("Workspace")
                        .HasForeignKey("LockedIn.DataAccess.Models.Workspace", "BookingId")
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_booking_id");

                    b.HasOne("LockedIn.DataAccess.Models.CustomerProfile", "Customer")
                        .WithMany("Workspaces")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_customer_id");

                    b.HasOne("LockedIn.DataAccess.Models.PtProfile", "PtProfile")
                        .WithMany("Workspaces")
                        .HasForeignKey("PtProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_pt_profile_id");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("PtProfile");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.WorkspaceSession", b =>
                {
                    b.HasOne("LockedIn.DataAccess.Models.Workspace", "Workspace")
                        .WithMany("WorkspaceSessions")
                        .HasForeignKey("WorkspaceId")
                        .IsRequired()
                        .HasConstraintName("fk_workspace_sessions_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Booking", b =>
                {
                    b.Navigation("Conversation");

                    b.Navigation("Dispute");

                    b.Navigation("Payment");

                    b.Navigation("Review");

                    b.Navigation("Settlement");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.CustomerProfile", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Conversations");

                    b.Navigation("Disputes");

                    b.Navigation("Reviews");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Dispute", b =>
                {
                    b.Navigation("DisputeEvidences");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Package", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Payment", b =>
                {
                    b.Navigation("PaymentWebhookLogs");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.PtProfile", b =>
                {
                    b.Navigation("AiUsageLogs");

                    b.Navigation("Bookings");

                    b.Navigation("Conversations");

                    b.Navigation("Disputes");

                    b.Navigation("MealPlans");

                    b.Navigation("Packages");

                    b.Navigation("PtDocuments");

                    b.Navigation("Reviews");

                    b.Navigation("Settlements");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CustomerProfileDeletedByNavigations");

                    b.Navigation("CustomerProfileUser");

                    b.Navigation("Disputes");

                    b.Navigation("InverseDeletedByNavigation");

                    b.Navigation("MealPlans");

                    b.Navigation("NotificationDeletedByNavigations");

                    b.Navigation("NotificationUsers");

                    b.Navigation("Packages");

                    b.Navigation("PtProfileDeletedByNavigations");

                    b.Navigation("PtProfileUser");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("LockedIn.DataAccess.Models.Workspace", b =>
                {
                    b.Navigation("MealPlans");

                    b.Navigation("WorkspaceSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
